### ISSUE TITLE
Is libelbrus.so library closed source?

### ISSUE THREAD

**Issue by jahaniam** [NVIDIA-ISAAC-ROS/isaac_ros_visual_slam#62]
Hi Team, 

Thank you for open-sourcing this package. In some workshops related to nvidia visual slam, I was under the impression that Nvidia Elbrus is open-source, but we noticed the backend main library [libelbrus.so](https://github.com/NVIDIA-ISAAC-ROS/isaac_ros_nitros/blob/main/isaac_ros_nitros/lib/elbrus/lib_x86_64/libelbrus.so) is still closed source. 

I was wondering if the library itself could be open-source as well. We would like to contribute, make some modifications, add some features, and use it in our production robot autonomy stack or if it is already open-sourced I appreciate it if you can point me to it.

Thank you,
Ali

**Comment by hemalshahNV** [comment]
Isaac ROS packages are mostly licensed ApacheV2 and available with source but we do not currently have plans to do so with libelbrus.so yet. Legal issues with licensing, patenting, and accepting contributions can be tricky when trying to open source a library like libelbrus rather than a bilateral agreement to share source with a specific company or individual. If you have any feature requests or modifications you'd like us to make, however, we would love to consider them for future versions of course.
