### ISSUE TITLE
realsense no images after splitter

### ISSUE THREAD

**Issue by ARK3r** [NVIDIA-ISAAC-ROS/isaac_ros_visual_slam#81]
OS: Ubuntu 22.04.2 LTS x86_64
Kernel: 5.19.0-38-generic

So I'm trying to get the [nvblox realsense example](https://github.com/NVIDIA-ISAAC-ROS/isaac_ros_nvblox/blob/main/docs/tutorial-realsense.md) working on my own PC using the dev docker container and I'm running into [this issue](https://github.com/NVIDIA-ISAAC-ROS/isaac_ros_nvblox/blob/main/docs/troubleshooting-nvblox-realsense.md#symptoms).

I assumed this is an issue closer to the visual slam package than nvblox so I'm posting it here, considering I'll probably run into the same issue if I try to run the visual slam package without nvblox.

I went through [the solution to the first check](https://github.com/NVIDIA-ISAAC-ROS/isaac_ros_nvblox/blob/main/docs/troubleshooting-nvblox-realsense.md#solution-1---install-dkms) and I did both solutions, both install through apt and then the .deb file and it wasn't working until it did. realsense-viewer is somehow showing metadata now.

So then I moved on to running the example again and now I'm running into the issue that the splitter is not showing any images.

I'm wondering what my next steps should be here.

**Comment by jaiveersinghNV** [comment]
Could you please provide the full set of logs from your experiments? This will help us hone in on the problem.

Additionally, could you please try running the VSLAM-only example using RealSense [here](https://github.com/NVIDIA-ISAAC-ROS/isaac_ros_visual_slam/blob/main/docs/tutorial-realsense.md#tutorial-for-visual-slam-using-a-realsense-camera)? If this tutorial works for you, then we can narrow down the issue to something with Isaac ROS Nvblox. 

As for your concern about the point cloud topics, this is expected behavior. When the pointcloud is configured to be off, the RealSense camera node will stop publishing to the `/camera/depth/color/points/` topic, and the Nvblox node will also stop subscribing to the `/camera/realsense_splitter_node/output/pointcloud` topic. The `realsense_splitter` node is merely a utility node; it won't cause any errors if the pointcloud topic remains empty.

**Comment by jn128c** [comment]
maybe I can save you some hours which I already spent...

Missed this step? 

> Stop git tracking the COLCON_IGNORE file in the realsense_splitter package and remove it.

    cd ~/workspaces/isaac_ros-dev/src/isaac_ros_nvblox/nvblox_examples/realsense_splitter && \
      git update-index --assume-unchanged COLCON_IGNORE && \
      rm COLCON_IGNORE

    Note: The COLCON_IGNORE file was added to remove the dependency to realsense-ros for users that do not want to run the RealSense examples."

For me it did the trick, before I had the same situation..
